# This is a basic workflow to help you get started with Actions
name: GitHub Environment Variables
on: [push]
jobs:
  my_job:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Default-environment-variables
        run: |    
          echo "CI=${{ env.CI }}."
